install:
  - choco install gitversion.portable -pre -y

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver

build:
  project: Pomona.sln

after_build:
  - ps: >-
      ./update-docs.ps1

test:
  assemblies:
    - 'tests/**/bin/*/*Tests.dll'
  categories:
    except:
      - TODO
